# GitHub will create PRs for JavaScript dependencies in the repo
# See https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates every week
    schedule:
      interval: "weekly"
    # Limit to 10 open PRs for dependencies
    open-pull-requests-limit: 10
    # Specify labels for pull requests for version updates
    labels:
      - "dependencies"
      - "npm"
    # Limit to security updates
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    # Group all minor and patch updates together
    groups:
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
